[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'miyakogi/seiya.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'hokaccha/vim-html5validator'

[[plugins]]
repo = 'gko/vim-coloresque'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'Lokaltog/vim-powerline'

[[plugins]]
repo = 'vim-jp/cpp-vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'Mizuchi/STL-Syntax'
