# プラグイン管理用
[[plugins]]
repo = 'Shougo/dein.vim'

# ステータスバー装飾
[[plugins]]
repo = 'itchyny/lightline.vim'

# 非同期処理を可能にする
[[plugins]]
repo = 'Shougo/vimproc'

# 行末のホワイトスペース可視化
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# javascript
[[plugins]]
repo = 'pangloss/vim-javascript'

# auto close
[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'alvan/vim-closetag'

# ALE
[[plugins]]
repo = 'w0rp/ale'

# ウィンドウサイズ変更プラグイン
[[plugins]]
repo = 'simeji/winresizer'

# 背景透過
[[plugins]]
repo = 'miyakogi/seiya.vim'

# sudo
[[plugins]]
repo = 'vim-scripts/sudo.vim'

# nginx
[[plugins]]
repo = 'chr4/nginx.vim'

# Golang
[[plugins]]
repo = 'fatih/vim-go'

# LSP
[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
